// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmGZRKlyp3VN4SU9MNKf7tXlaufKYzrM',
    appId: '1:497729192904:web:f9c696cb33c10f4df776fd',
    messagingSenderId: '497729192904',
    projectId: 'notes-lelo',
    authDomain: 'notes-lelo.firebaseapp.com',
    databaseURL: 'https://notes-lelo-default-rtdb.firebaseio.com',
    storageBucket: 'notes-lelo.appspot.com',
    measurementId: 'G-01HCSCYBZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZOHRSgbh-Lre7l9AzpdF24UXfRs7mBo',
    appId: '1:497729192904:android:072e257daeb96da0f776fd',
    messagingSenderId: '497729192904',
    projectId: 'notes-lelo',
    databaseURL: 'https://notes-lelo-default-rtdb.firebaseio.com',
    storageBucket: 'notes-lelo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClwRNosXqVpUM3lEfR7rBuVD38SpSMt-s',
    appId: '1:497729192904:ios:8e807b58584dcf5df776fd',
    messagingSenderId: '497729192904',
    projectId: 'notes-lelo',
    databaseURL: 'https://notes-lelo-default-rtdb.firebaseio.com',
    storageBucket: 'notes-lelo.appspot.com',
    androidClientId: '497729192904-omf2pi5825gdajpmp785liqa9j72rjjv.apps.googleusercontent.com',
    iosClientId: '497729192904-rgquvhhejiknqg82tl5devtdr03grdtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClwRNosXqVpUM3lEfR7rBuVD38SpSMt-s',
    appId: '1:497729192904:ios:45950d8dd50d254af776fd',
    messagingSenderId: '497729192904',
    projectId: 'notes-lelo',
    databaseURL: 'https://notes-lelo-default-rtdb.firebaseio.com',
    storageBucket: 'notes-lelo.appspot.com',
    androidClientId: '497729192904-omf2pi5825gdajpmp785liqa9j72rjjv.apps.googleusercontent.com',
    iosClientId: '497729192904-mu60v41c0gl0kv77euc3koaqrchebn6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
